version: 2
jobs:
  build:
    working_directory: /root/batavia/
    docker:
      - image: circleci/node:4.8.2
      - image: python:3.4.4
        environment:
            TZ: "Australia/Perth"
    steps:
     # - run: 
     #     name: "prereq"
     #     command: "apt-get install git"
      - run: 
          name: "PyTest"
          command: "pip install pytest" # git+https://github.com/pybee/pytest-circleci"

      - checkout
        
      - run: 
          name: "Tests"
          command: "py.test tests"

      - run: 
          name: "Linting"
          command: "node_modules/.bin/eslint batavia"
