version: 2
jobs:
  build:
    docker:
      - image: python:3.4.6-slim
        environment:
            TZ: "Australia/Perth"
    steps:
      - run:
          name: "npm"
          command: "npm install -g npm && npm install"

      - run: 
          name: "PyTest"
          command: "pip install pytest git+https://github.com/pybee/pytest-circleci"
        
      - run: 
          name: "Tests"
          command: "py.test tests"

      - run: 
          name: "Linting"
          command: "node_modules/.bin/eslint batavia"
