version: 2
jobs:
  build:
    working_directory: /tmp/batavia
    docker:
      - image: python:3.4
        environment:
            TZ: "Australia/Perth"
    steps:
      - checkout
    
      - run: 
          name: "node"
          command: "curl -sL https://deb.nodesource.com/setup_6.x && apt-get install -y nodejs"

      - run:
          name: "npm"
          command: "npm install -g npm && npm install"
      #- run:
      #    name: "setup"
      #    command: "apt-get install python-pip && pip install -U pip setuptools"
      - run: 
          name: "PyTest"
          command: "pip install pytest git+https://github.com/pybee/pytest-circleci"
  
      - run: 
          name: "test"
          command: "py.test tests"

      - run: 
          name: "eslint"
          command: "node_modules/.bin/eslint batavia"
