version: 2
jobs:
  build:
    working_directory: /tmp/batavia
    docker:
      - image: circleci/node:4.8.2
      - image: python:3.4.4
        environment:
            TZ: "Australia/Perth"
    steps:
     # - run: 
     #     name: "prereq"
     #     command: "apt-get install git"
     # - run: 
     #     name: "PyTest"
     #     command: "pip install pytest" # git+https://github.com/pybee/pytest-circleci"

      - checkout
    
      - run:
          name: "setup"
          command: "pip install -U pip setuptools"
  
      - run: 
          name: "test"
          command: "python setup.py test" #py.test tests"

      - run: 
          name: "eslint"
          command: "node_modules/.bin/eslint batavia"
